// <auto-generated />
namespace MeAnota.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IndiceUsuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndiceUsuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201209302353425_IndiceUsuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
